<?php


/**
 * [BEGIN_COT_EXT]
 * Code=pagemasseditor
 * Name=Page Mass Editor
 * Description=Edit at once more than one page
 * Version=1.0.0
 * Date=2012-04-10
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * Requires_modules=page
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin pagemasseditor for Cotonti Siena
 * 
 * @package pagemasseditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>