<?php

/**
 * plugin pagemasseditor for Cotonti Siena
 * 
 * @package pagemasseditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

$def_config = array(
	'c' => 'shop',
	'in' => true,
	'filter' => 'validated',
	'title' => '',
	'sorttype' => 'title',
	'sortway' => 'asc'
	
);