<?php

/**
 * plugin pagemasseditor for Cotonti Siena
 * 
 * @package pagemasseditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_incfile('pagemasseditor', 'plug', 'fields');
require_once cot_incfile('pagemasseditor', 'plug', 'config');
require_once cot_langfile('pagemasseditor', 'plug');
require_once cot_incfile('page', 'module');
require_once cot_incfile('forms');


function cot_import_request ($name, $filter)
{
	global $def_config;
	if(isset($_REQUEST[$name]))
	{
		$val = cot_import($name, 'R', $filter);
	}
	else
	{
		$val = $def_config[$name];
	}
	if ($filter == "BOL")
	{
		$val = ($val) ? 1 : 0;
	}
	return $val;
}
