<?php

/**
 * plugin pagemasseditor for Cotonti Siena
 * 
 * @package pagemasseditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
$page_fields = array();

$page_fields['keywords'] = array('type' => 'TXT');
$page_fields['alias'] = array('type' => 'TXT');
$page_fields['title'] = array('type' => 'TXT');
$page_fields['desc'] = array('type' => 'TXT');
$page_fields['text'] = array('type' => 'TXT');
$page_fields['parser'] = array('type' => 'TXT');
$page_fields['author'] = array('type' => 'TXT');
$page_fields['file'] = array('type' => 'TXT');
$page_fields['url'] = array('type' => 'TXT');
$page_fields['size'] = array('type' => 'TXT');
$page_fields['file'] = array('type' => 'TXT');
$page_fields['cat'] = array('type' => 'TXT');
$page_fields['date'] = array('type' => 'INT');
$page_fields['begin'] = array('type' => 'INT');
$page_fields['expire'] = array('type' => 'INT');
$page_fields['updated'] = array('type' => 'INT');
$page_fields['state'] = array('type' => 'INT');
$page_fields['alias'] = array('type' => 'TXT');
$page_fields['count'] = array('type' => 'INT');
$page_fields['ownerid'] = array('type' => 'INT');
$page_fields['filecount'] = array('type' => 'INT');

foreach ($cot_extrafields[$db_pages] as $exfld)
{
	$page_fields[$exfld['field_name']] = array('type' => 'TXT');
}


					